import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// fff
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <h1>welcome</h1>
     </div>

  )
}
